function checkLuckyNumber(num) {
  // TODO: Create and return a promise that:
  // 1. Waits 800ms (use setTimeout)
  // 2. Resolves with "Lucky!" if number is divisible by 7
  // 3. Resolves with "Not lucky" for other positive numbers
  // 4. Rejects with Error("Invalid number") if number is negative or zero
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (num!= 0 && num % 7 === 0) {
        resolve("Lucky!");
      } else if (num > 0) {
        resolve("Not lucky!");
      } else {
        reject(new Error("Invalid number"));
      }
    }, 800);
  });
}

checkLuckyNumber(0)
  .then((msg) => console.log(msg))
  .catch((err) => console.log(err.message));
